sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: OkwodfOeNXwRzB3de7J8tiHCiKW9xmXyesbu/5hJtL/WLd3dBQ5Sfwr387e1nDv6udpCC1t7+b4t+Fvc1mzI7T4bvlDDQphFXa4ADKOJvN3MmPkPfENc99EsohzVdvFtPaq6iLzaqWJYyXl9WhkagI0NamOGfCx11+7aCw0u6Zhq590QF0Sz6gDipl9r+hQXthMdafVpmRAEmD5XH11s8tEXr7K9I5ZZj1CtUM9Ptoa6jffUuTgG2s71MB0wSon5/xv1oXCN80SOJvVFXSPcn6lHCxrGUshUz4Ayal1SnniL6lYVXr7aEWI+LLg/Z9Wpm56DLD1HRX9aIq11+vIFPsro+t5lRtyw7jnreoRF5plRA3dwFtQNzcDlOZRBm9SAX0WpEmR4nBW+qJaROsr7+1a561Hk6m+c9yiYYnFAuI23EWCLM6sQadEQEpFiw+lR2DwzcsxBK7DeBuT2iXGX9nU5IwIouZuM6m1PYmwhGknxWjYM3hy/9sCzW5q5/fp7aBvRrdBJ9Xq6WabkZvyKPQMXKDdn4MBH4xOiCiFEJm1B8O0iG+xXTzm0MXcuhG29z24W0HNzWC6Gr3yVDu74sfP2hpIpHBdgKDNaxNumreQqhGwndVt7xnbv5/dMOgJOXB6aMeCGo0LvBKqEUfyE+H45D8W+pg6Kaex00MllzrU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Fanny-and-the-Servant-Problem_2829
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy